export const ALT_USER_DATA = 'ALT_USER_DATA'
export const ALT_USER_PERMISSION_DATA = 'ALT_USER_PERMISSION_DATA'
export const ALT_COMPANY_DATA = 'ALT_COMPANY_DATA'
export const ALT_AUTH_STATE = 'ALT_AUTH_STATE'

export const ALT_USER_LISTS = 'ALT_USER_LISTS'
export const ALT_PRODUCT_LISTS = 'ALT_PRODUCT_LISTS'
export const ALT_GROUP_LISTS = 'ALT_GROUP_LISTS'
export const ALT_MODAL_LISTS = 'ALT_MODAL_LISTS'
export const ALT_COMPANY_LISTS = 'ALT_COMPANY_LISTS'
export const ALT_TRANSACTION_LISTS = 'ALT_TRANSACTION_LISTS'
export const ALT_FRAUD_CASES = 'ALT_FRAUD_CASES'
export const ALT_DEVICE_LISTS = 'ALT_DEVICE_LISTS'
export const LOGOUT = 'LOGOUT'


export const ALT_DASH_STATS = 'ALT_DASH_STATS'
export const CLEAR_DASHBOARD = 'CLEAR_DASHBOARD'
